// <auto-generated />
using System;
using FmpBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FmpBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("availability_status");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric")
                        .HasColumnName("average_rating");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CurrentFleetOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_fleet_owner_id");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_expiry_date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalTripsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("total_trips_completed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessInstructions")
                        .HasColumnType("text")
                        .HasColumnName("access_instructions");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("text")
                        .HasColumnName("contact_person_name");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("India")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Landmark")
                        .HasColumnType("text")
                        .HasColumnName("landmark");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("text")
                        .HasColumnName("operating_hours");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("addresses", null, t =>
                        {
                            t.HasCheckConstraint("valid_owner_type", "owner_type IN ('user', 'organization')");
                        });
                });

            modelBuilder.Entity("FmpBackend.Models.DriverQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ClaimWindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_window_end");

                    b.Property<DateTime>("ClaimWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_window_start");

                    b.Property<int>("ClaimableCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("claimable_count");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<bool>("HasClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_claimed");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QueueEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_event_id");

                    b.Property<string>("ShipmentListJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("shipment_list_json");

                    b.HasKey("Id");

                    b.ToTable("driver_queue_entries", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.FleetOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("business_contact_email");

                    b.Property<string>("BusinessContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("business_contact_phone");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessType")
                        .HasColumnType("text")
                        .HasColumnName("business_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.ToTable("fleet_owners", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GstNumber")
                        .HasColumnType("text")
                        .HasColumnName("gst_number");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_type");

                    b.Property<string>("PanNumber")
                        .HasColumnType("text")
                        .HasColumnName("pan_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("PrimaryContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_email");

                    b.Property<string>("PrimaryContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_name");

                    b.Property<string>("PrimaryContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_phone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.QueueEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("PriorityRule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("highest_trips")
                        .HasColumnName("priority_rule");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("live")
                        .HasColumnName("status");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("window_seconds");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.ToTable("queue_events", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AdminOverrideAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admin_override_at");

                    b.Property<Guid?>("AdminOverrideBy")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_override_by");

                    b.Property<decimal?>("AgreedPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("agreed_price");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CargoDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo_description");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo_type");

                    b.Property<decimal?>("CargoVolumeCubicMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cargo_volume_cubic_meters");

                    b.Property<decimal>("CargoWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cargo_weight_kg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DropAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("drop_address_id");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<decimal>("LoadingCharges")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("loading_charges");

                    b.Property<decimal>("OtherCharges")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("other_charges");

                    b.Property<int?>("PackageCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<Guid>("PickupAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_address_id");

                    b.Property<DateTime?>("PreferredDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_delivery_date");

                    b.Property<DateTime?>("PreferredPickupDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_pickup_date");

                    b.Property<string>("PricePerUnit")
                        .HasColumnType("text")
                        .HasColumnName("price_per_unit");

                    b.Property<Guid>("ReceiverOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_organization_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<bool>("RequiresInsurance")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_insurance");

                    b.Property<bool>("RequiresRefrigeration")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_refrigeration");

                    b.Property<Guid>("SenderOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_organization_id");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shipment_number");

                    b.Property<string>("SpecialHandlingInstructions")
                        .HasColumnType("text")
                        .HasColumnName("special_handling_instructions");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalEstimatedPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_estimated_price");

                    b.Property<decimal>("UnloadingCharges")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unloading_charges");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UpdatedByAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("updated_by_admin");

                    b.HasKey("Id");

                    b.HasIndex("DropAddressId");

                    b.HasIndex("PickupAddressId");

                    b.HasIndex("ReceiverOrganizationId");

                    b.HasIndex("SenderOrganizationId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.ShipmentQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CurrentDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_driver_id");

                    b.Property<DateTime?>("OfferExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_expires_at");

                    b.Property<string>("RequiredVehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("required_vehicle_type");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("waiting")
                        .HasColumnName("status");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_queue", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.ShipmentQueueAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<int>("DriverPosition")
                        .HasColumnType("integer")
                        .HasColumnName("driver_position");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("outcome");

                    b.Property<Guid>("QueueEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_event_id");

                    b.Property<Guid>("ShipmentQueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_queue_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("QueueEventId");

                    b.HasIndex("ShipmentQueueId");

                    b.ToTable("shipment_queue_assignments", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("actor_type_enum")
                        .HasColumnName("actor_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("system_logs", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualDistanceKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("actual_distance_km");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_time");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_time");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("AssignedFleetOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_fleet_owner_id");

                    b.Property<Guid?>("AssignedUnionId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_union_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("current_latitude");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("current_longitude");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("created")
                        .HasColumnName("current_status");

                    b.Property<string>("DelayReason")
                        .HasColumnType("text")
                        .HasColumnName("delay_reason");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveredToName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("delivered_to_name");

                    b.Property<string>("DeliveredToPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivered_to_phone");

                    b.Property<string>("DeliveryNotes")
                        .HasColumnType("text")
                        .HasColumnName("delivery_notes");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("DriverPaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("driver_paid_at");

                    b.Property<decimal?>("DriverPaymentAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("driver_payment_amount");

                    b.Property<string>("DriverPaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("driver_payment_status");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_distance_km");

                    b.Property<decimal?>("EstimatedDurationHours")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("estimated_duration_hours");

                    b.Property<bool>("HasIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_issues");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("text")
                        .HasColumnName("issue_description");

                    b.Property<DateTime?>("LastLocationUpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_location_update_at");

                    b.Property<DateTime?>("PlannedEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_time");

                    b.Property<DateTime?>("PlannedStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_time");

                    b.Property<string>("ProofOfDeliveryUrl")
                        .HasColumnType("text")
                        .HasColumnName("proof_of_delivery_url");

                    b.Property<string>("ReceiverFeedback")
                        .HasColumnType("text")
                        .HasColumnName("receiver_feedback");

                    b.Property<int?>("ReceiverRating")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_rating");

                    b.Property<string>("SenderFeedback")
                        .HasColumnType("text")
                        .HasColumnName("sender_feedback");

                    b.Property<int?>("SenderRating")
                        .HasColumnType("integer")
                        .HasColumnName("sender_rating");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trip_number");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnionId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("DriverId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("TripNumber")
                        .IsUnique();

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AuthProviderId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("availability_status");

                    b.Property<decimal?>("CapacityTons")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity_tons");

                    b.Property<Guid?>("CurrentDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_driver_id");

                    b.Property<Guid>("FleetOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("fleet_owner_id");

                    b.Property<decimal?>("MaxLoadWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("max_load_weight_kg");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("FmpBackend.Models.Shipment", b =>
                {
                    b.HasOne("FmpBackend.Models.Address", "DropAddress")
                        .WithMany()
                        .HasForeignKey("DropAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_drop_address");

                    b.HasOne("FmpBackend.Models.Address", "PickupAddress")
                        .WithMany()
                        .HasForeignKey("PickupAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_pickup_address");

                    b.HasOne("FmpBackend.Models.Organization", "ReceiverOrganization")
                        .WithMany()
                        .HasForeignKey("ReceiverOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_receiver_org");

                    b.HasOne("FmpBackend.Models.Organization", "SenderOrganization")
                        .WithMany()
                        .HasForeignKey("SenderOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_sender_org");

                    b.Navigation("DropAddress");

                    b.Navigation("PickupAddress");

                    b.Navigation("ReceiverOrganization");

                    b.Navigation("SenderOrganization");
                });

            modelBuilder.Entity("FmpBackend.Models.ShipmentQueue", b =>
                {
                    b.HasOne("FmpBackend.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("FmpBackend.Models.ShipmentQueueAssignment", b =>
                {
                    b.HasOne("FmpBackend.Models.QueueEvent", "QueueEvent")
                        .WithMany()
                        .HasForeignKey("QueueEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmpBackend.Models.ShipmentQueue", "ShipmentQueue")
                        .WithMany()
                        .HasForeignKey("ShipmentQueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueEvent");

                    b.Navigation("ShipmentQueue");
                });

            modelBuilder.Entity("FmpBackend.Models.Trip", b =>
                {
                    b.HasOne("FmpBackend.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });
#pragma warning restore 612, 618
        }
    }
}
